// @ts-nocheck
/* eslint-disable */
/* tslint:disable */
/* prettier-ignore-start */

/** @jsxRuntime classic */
/** @jsx createPlasmicElementProxy */
/** @jsxFrag React.Fragment */

// This class is auto-generated by Plasmic; please do not edit!
// Plasmic Project: sAm7j9mZDvyUmEcguggAEZ
// Component: CQD8Pxr96jbL

import * as React from "react";

import Head from "next/head";
import Link, { LinkProps } from "next/link";
import { useRouter } from "next/router";

import {
  Flex as Flex__,
  MultiChoiceArg,
  PlasmicDataSourceContextProvider as PlasmicDataSourceContextProvider__,
  PlasmicIcon as PlasmicIcon__,
  PlasmicImg as PlasmicImg__,
  PlasmicLink as PlasmicLink__,
  PlasmicPageGuard as PlasmicPageGuard__,
  SingleBooleanChoiceArg,
  SingleChoiceArg,
  Stack as Stack__,
  StrictProps,
  Trans as Trans__,
  classNames,
  createPlasmicElementProxy,
  deriveRenderOpts,
  ensureGlobalVariants,
  generateOnMutateForSpec,
  generateStateOnChangeProp,
  generateStateOnChangePropForCodeComponents,
  generateStateValueProp,
  get as $stateGet,
  hasVariant,
  initializeCodeComponentStates,
  initializePlasmicStates,
  makeFragment,
  omit,
  pick,
  renderPlasmicSlot,
  set as $stateSet,
  useCurrentUser,
  useDollarState,
  usePlasmicTranslator,
  useTrigger,
  wrapWithClassName
} from "@plasmicapp/react-web";
import {
  DataCtxReader as DataCtxReader__,
  useDataEnv,
  useGlobalActions
} from "@plasmicapp/react-web/lib/host";

import Mobile1 from "../../Mobile1"; // plasmic-import: V5wBCgG6NMHK/component
import Mobile2 from "../../Mobile2"; // plasmic-import: Ya1Lo3itYxCg/component
import Desktop1 from "../../Desktop1"; // plasmic-import: cAXqSs1VbbDV/component
import Desktop2 from "../../Desktop2"; // plasmic-import: 9FFQvMvxZbIZ/component
import Desktop6 from "../../Desktop6"; // plasmic-import: GuyG08-Cxz2f/component
import Desktop3 from "../../Desktop3"; // plasmic-import: 12wSeGIcfcjG/component
import Desktop5 from "../../Desktop5"; // plasmic-import: MSMlbw5YAR6C/component
import MobilePreletores from "../../MobilePreletores"; // plasmic-import: KxCAyuU4Ni_B/component

import { useScreenVariants as useScreenVariantswbSvjcbuSqcK } from "./PlasmicGlobalVariant__Screen"; // plasmic-import: WbSvjcbuSqcK/globalVariant

import "@plasmicapp/react-web/lib/plasmic.css";

import projectcss from "./plasmic.module.css"; // plasmic-import: sAm7j9mZDvyUmEcguggAEZ/projectcss
import sty from "./PlasmicHomepage.module.css"; // plasmic-import: CQD8Pxr96jbL/css

createPlasmicElementProxy;

export type PlasmicHomepage__VariantMembers = {};
export type PlasmicHomepage__VariantsArgs = {};
type VariantPropType = keyof PlasmicHomepage__VariantsArgs;
export const PlasmicHomepage__VariantProps = new Array<VariantPropType>();

export type PlasmicHomepage__ArgsType = {};
type ArgPropType = keyof PlasmicHomepage__ArgsType;
export const PlasmicHomepage__ArgProps = new Array<ArgPropType>();

export type PlasmicHomepage__OverridesType = {
  root?: Flex__<"div">;
  mobile1?: Flex__<typeof Mobile1>;
  mobile2?: Flex__<typeof Mobile2>;
  desktop1?: Flex__<typeof Desktop1>;
  desktop2?: Flex__<typeof Desktop2>;
  desktop6?: Flex__<typeof Desktop6>;
  desktop3?: Flex__<typeof Desktop3>;
  desktop5?: Flex__<typeof Desktop5>;
  mobilePreletores?: Flex__<typeof MobilePreletores>;
};

export interface DefaultHomepageProps {}

const $$ = {};

function useNextRouter() {
  try {
    return useRouter();
  } catch {}
  return undefined;
}

function PlasmicHomepage__RenderFunc(props: {
  variants: PlasmicHomepage__VariantsArgs;
  args: PlasmicHomepage__ArgsType;
  overrides: PlasmicHomepage__OverridesType;
  forNode?: string;
}) {
  const { variants, overrides, forNode } = props;

  const args = React.useMemo(
    () =>
      Object.assign(
        {},
        Object.fromEntries(
          Object.entries(props.args).filter(([_, v]) => v !== undefined)
        )
      ),
    [props.args]
  );

  const $props = {
    ...args,
    ...variants
  };

  const __nextRouter = useNextRouter();
  const $ctx = useDataEnv?.() || {};
  const refsRef = React.useRef({});
  const $refs = refsRef.current;

  const globalVariants = ensureGlobalVariants({
    screen: useScreenVariantswbSvjcbuSqcK()
  });

  return (
    <React.Fragment>
      <Head></Head>

      <style>{`
        body {
          margin: 0;
        }
      `}</style>

      <div className={projectcss.plasmic_page_wrapper}>
        <div
          data-plasmic-name={"root"}
          data-plasmic-override={overrides.root}
          data-plasmic-root={true}
          data-plasmic-for-node={forNode}
          className={classNames(
            projectcss.all,
            projectcss.root_reset,
            projectcss.plasmic_default_styles,
            projectcss.plasmic_mixins,
            projectcss.plasmic_tokens,
            sty.root
          )}
        >
          <Mobile1
            data-plasmic-name={"mobile1"}
            data-plasmic-override={overrides.mobile1}
            className={classNames("__wab_instance", sty.mobile1)}
          />

          <Mobile2
            data-plasmic-name={"mobile2"}
            data-plasmic-override={overrides.mobile2}
            className={classNames("__wab_instance", sty.mobile2)}
          />

          <Desktop1
            data-plasmic-name={"desktop1"}
            data-plasmic-override={overrides.desktop1}
            className={classNames("__wab_instance", sty.desktop1)}
          />

          <Desktop2
            data-plasmic-name={"desktop2"}
            data-plasmic-override={overrides.desktop2}
            className={classNames("__wab_instance", sty.desktop2)}
          />

          <Desktop6
            data-plasmic-name={"desktop6"}
            data-plasmic-override={overrides.desktop6}
            className={classNames("__wab_instance", sty.desktop6)}
          />

          <Desktop3
            data-plasmic-name={"desktop3"}
            data-plasmic-override={overrides.desktop3}
            className={classNames("__wab_instance", sty.desktop3)}
          />

          <Desktop5
            data-plasmic-name={"desktop5"}
            data-plasmic-override={overrides.desktop5}
            className={classNames("__wab_instance", sty.desktop5)}
          />

          <MobilePreletores
            data-plasmic-name={"mobilePreletores"}
            data-plasmic-override={overrides.mobilePreletores}
            className={classNames("__wab_instance", sty.mobilePreletores)}
          />
        </div>
      </div>
    </React.Fragment>
  ) as React.ReactElement | null;
}

const PlasmicDescendants = {
  root: [
    "root",
    "mobile1",
    "mobile2",
    "desktop1",
    "desktop2",
    "desktop6",
    "desktop3",
    "desktop5",
    "mobilePreletores"
  ],
  mobile1: ["mobile1"],
  mobile2: ["mobile2"],
  desktop1: ["desktop1"],
  desktop2: ["desktop2"],
  desktop6: ["desktop6"],
  desktop3: ["desktop3"],
  desktop5: ["desktop5"],
  mobilePreletores: ["mobilePreletores"]
} as const;
type NodeNameType = keyof typeof PlasmicDescendants;
type DescendantsType<T extends NodeNameType> =
  (typeof PlasmicDescendants)[T][number];
type NodeDefaultElementType = {
  root: "div";
  mobile1: typeof Mobile1;
  mobile2: typeof Mobile2;
  desktop1: typeof Desktop1;
  desktop2: typeof Desktop2;
  desktop6: typeof Desktop6;
  desktop3: typeof Desktop3;
  desktop5: typeof Desktop5;
  mobilePreletores: typeof MobilePreletores;
};

type ReservedPropsType = "variants" | "args" | "overrides";
type NodeOverridesType<T extends NodeNameType> = Pick<
  PlasmicHomepage__OverridesType,
  DescendantsType<T>
>;
type NodeComponentProps<T extends NodeNameType> =
  // Explicitly specify variants, args, and overrides as objects
  {
    variants?: PlasmicHomepage__VariantsArgs;
    args?: PlasmicHomepage__ArgsType;
    overrides?: NodeOverridesType<T>;
  } & Omit<PlasmicHomepage__VariantsArgs, ReservedPropsType> & // Specify variants directly as props
    /* Specify args directly as props*/ Omit<
      PlasmicHomepage__ArgsType,
      ReservedPropsType
    > &
    /* Specify overrides for each element directly as props*/ Omit<
      NodeOverridesType<T>,
      ReservedPropsType | VariantPropType | ArgPropType
    > &
    /* Specify props for the root element*/ Omit<
      Partial<React.ComponentProps<NodeDefaultElementType[T]>>,
      ReservedPropsType | VariantPropType | ArgPropType | DescendantsType<T>
    >;

function makeNodeComponent<NodeName extends NodeNameType>(nodeName: NodeName) {
  type PropsType = NodeComponentProps<NodeName> & { key?: React.Key };
  const func = function <T extends PropsType>(
    props: T & StrictProps<T, PropsType>
  ) {
    const { variants, args, overrides } = React.useMemo(
      () =>
        deriveRenderOpts(props, {
          name: nodeName,
          descendantNames: PlasmicDescendants[nodeName],
          internalArgPropNames: PlasmicHomepage__ArgProps,
          internalVariantPropNames: PlasmicHomepage__VariantProps
        }),
      [props, nodeName]
    );
    return PlasmicHomepage__RenderFunc({
      variants,
      args,
      overrides,
      forNode: nodeName
    });
  };
  if (nodeName === "root") {
    func.displayName = "PlasmicHomepage";
  } else {
    func.displayName = `PlasmicHomepage.${nodeName}`;
  }
  return func;
}

export const PlasmicHomepage = Object.assign(
  // Top-level PlasmicHomepage renders the root element
  makeNodeComponent("root"),
  {
    // Helper components rendering sub-elements
    mobile1: makeNodeComponent("mobile1"),
    mobile2: makeNodeComponent("mobile2"),
    desktop1: makeNodeComponent("desktop1"),
    desktop2: makeNodeComponent("desktop2"),
    desktop6: makeNodeComponent("desktop6"),
    desktop3: makeNodeComponent("desktop3"),
    desktop5: makeNodeComponent("desktop5"),
    mobilePreletores: makeNodeComponent("mobilePreletores"),

    // Metadata about props expected for PlasmicHomepage
    internalVariantProps: PlasmicHomepage__VariantProps,
    internalArgProps: PlasmicHomepage__ArgProps,

    // Page metadata
    pageMetadata: {
      title: "",
      description: "",
      ogImageSrc: "",
      canonical: ""
    }
  }
);

export default PlasmicHomepage;
/* prettier-ignore-end */
