// @ts-nocheck
/* eslint-disable */
/* tslint:disable */
/* prettier-ignore-start */

/** @jsxRuntime classic */
/** @jsx createPlasmicElementProxy */
/** @jsxFrag React.Fragment */

// This class is auto-generated by Plasmic; please do not edit!
// Plasmic Project: sAm7j9mZDvyUmEcguggAEZ
// Component: KxCAyuU4Ni_B

import * as React from "react";

import Head from "next/head";
import Link, { LinkProps } from "next/link";
import { useRouter } from "next/router";

import {
  Flex as Flex__,
  MultiChoiceArg,
  PlasmicDataSourceContextProvider as PlasmicDataSourceContextProvider__,
  PlasmicIcon as PlasmicIcon__,
  PlasmicImg as PlasmicImg__,
  PlasmicLink as PlasmicLink__,
  PlasmicPageGuard as PlasmicPageGuard__,
  SingleBooleanChoiceArg,
  SingleChoiceArg,
  Stack as Stack__,
  StrictProps,
  Trans as Trans__,
  classNames,
  createPlasmicElementProxy,
  deriveRenderOpts,
  ensureGlobalVariants,
  generateOnMutateForSpec,
  generateStateOnChangeProp,
  generateStateOnChangePropForCodeComponents,
  generateStateValueProp,
  get as $stateGet,
  hasVariant,
  initializeCodeComponentStates,
  initializePlasmicStates,
  makeFragment,
  omit,
  pick,
  renderPlasmicSlot,
  set as $stateSet,
  useCurrentUser,
  useDollarState,
  usePlasmicTranslator,
  useTrigger,
  wrapWithClassName
} from "@plasmicapp/react-web";
import {
  DataCtxReader as DataCtxReader__,
  useDataEnv,
  useGlobalActions
} from "@plasmicapp/react-web/lib/host";

import { useScreenVariants as useScreenVariantswbSvjcbuSqcK } from "./PlasmicGlobalVariant__Screen"; // plasmic-import: WbSvjcbuSqcK/globalVariant

import "@plasmicapp/react-web/lib/plasmic.css";

import projectcss from "./plasmic.module.css"; // plasmic-import: sAm7j9mZDvyUmEcguggAEZ/projectcss
import sty from "./PlasmicMobilePreletores.module.css"; // plasmic-import: KxCAyuU4Ni_B/css

createPlasmicElementProxy;

export type PlasmicMobilePreletores__VariantMembers = {};
export type PlasmicMobilePreletores__VariantsArgs = {};
type VariantPropType = keyof PlasmicMobilePreletores__VariantsArgs;
export const PlasmicMobilePreletores__VariantProps =
  new Array<VariantPropType>();

export type PlasmicMobilePreletores__ArgsType = {};
type ArgPropType = keyof PlasmicMobilePreletores__ArgsType;
export const PlasmicMobilePreletores__ArgProps = new Array<ArgPropType>();

export type PlasmicMobilePreletores__OverridesType = {
  root?: Flex__<"div">;
};

export interface DefaultMobilePreletoresProps {
  className?: string;
}

const $$ = {};

function useNextRouter() {
  try {
    return useRouter();
  } catch {}
  return undefined;
}

function PlasmicMobilePreletores__RenderFunc(props: {
  variants: PlasmicMobilePreletores__VariantsArgs;
  args: PlasmicMobilePreletores__ArgsType;
  overrides: PlasmicMobilePreletores__OverridesType;
  forNode?: string;
}) {
  const { variants, overrides, forNode } = props;

  const args = React.useMemo(
    () =>
      Object.assign(
        {},
        Object.fromEntries(
          Object.entries(props.args).filter(([_, v]) => v !== undefined)
        )
      ),
    [props.args]
  );

  const $props = {
    ...args,
    ...variants
  };

  const __nextRouter = useNextRouter();
  const $ctx = useDataEnv?.() || {};
  const refsRef = React.useRef({});
  const $refs = refsRef.current;

  const globalVariants = ensureGlobalVariants({
    screen: useScreenVariantswbSvjcbuSqcK()
  });

  return (
    <div
      data-plasmic-name={"root"}
      data-plasmic-override={overrides.root}
      data-plasmic-root={true}
      data-plasmic-for-node={forNode}
      className={classNames(
        projectcss.all,
        projectcss.root_reset,
        projectcss.plasmic_default_styles,
        projectcss.plasmic_mixins,
        projectcss.plasmic_tokens,
        sty.root
      )}
    >
      <Stack__
        as={"div"}
        hasGap={true}
        className={classNames(projectcss.all, sty.freeBox__r6Nv)}
      >
        <div
          className={classNames(
            projectcss.all,
            projectcss.__wab_text,
            sty.text__iJNin
          )}
        >
          {"Preletores"}
        </div>
        <Stack__
          as={"div"}
          hasGap={true}
          className={classNames(projectcss.all, sty.freeBox___2FbHa)}
        >
          <Stack__
            as={"div"}
            hasGap={true}
            className={classNames(projectcss.all, sty.freeBox___4Ua7C)}
          >
            <PlasmicImg__
              alt={""}
              className={classNames(sty.img__ibeak)}
              displayHeight={"auto"}
              displayMaxHeight={"none"}
              displayMaxWidth={"100%"}
              displayMinHeight={"0"}
              displayMinWidth={"0"}
              displayWidth={"80%"}
              loading={"lazy"}
              src={{
                src: "/plasmic/casais/images/daniel.png",
                fullWidth: 1290,
                fullHeight: 1052,
                aspectRatio: undefined
              }}
              style={
                hasVariant(globalVariants, "screen", "mobileOnly")
                  ? { aspectRatio: 1, width: "80%" }
                  : undefined
              }
            />

            <div
              className={classNames(
                projectcss.all,
                projectcss.__wab_text,
                sty.text__niBul
              )}
            >
              {"Daniel e Selma Souza"}
            </div>
          </Stack__>
          <Stack__
            as={"div"}
            hasGap={true}
            className={classNames(projectcss.all, sty.freeBox___4EGcy)}
          >
            <PlasmicImg__
              alt={""}
              className={classNames(sty.img__zrj6Z)}
              displayHeight={"auto"}
              displayMaxHeight={"none"}
              displayMaxWidth={"100%"}
              displayMinHeight={"0"}
              displayMinWidth={"0"}
              displayWidth={"80%"}
              loading={"lazy"}
              src={{
                src: "/plasmic/casais/images/janPng.png",
                fullWidth: 1217,
                fullHeight: 1230,
                aspectRatio: undefined
              }}
              style={
                hasVariant(globalVariants, "screen", "mobileOnly")
                  ? { width: "80%", aspectRatio: 1 }
                  : undefined
              }
            />

            <div
              className={classNames(
                projectcss.all,
                projectcss.__wab_text,
                sty.text__kJzTw
              )}
            >
              {"Jan e Martha Gottfridsson"}
            </div>
          </Stack__>
        </Stack__>
      </Stack__>
    </div>
  ) as React.ReactElement | null;
}

const PlasmicDescendants = {
  root: ["root"]
} as const;
type NodeNameType = keyof typeof PlasmicDescendants;
type DescendantsType<T extends NodeNameType> =
  (typeof PlasmicDescendants)[T][number];
type NodeDefaultElementType = {
  root: "div";
};

type ReservedPropsType = "variants" | "args" | "overrides";
type NodeOverridesType<T extends NodeNameType> = Pick<
  PlasmicMobilePreletores__OverridesType,
  DescendantsType<T>
>;
type NodeComponentProps<T extends NodeNameType> =
  // Explicitly specify variants, args, and overrides as objects
  {
    variants?: PlasmicMobilePreletores__VariantsArgs;
    args?: PlasmicMobilePreletores__ArgsType;
    overrides?: NodeOverridesType<T>;
  } & Omit<PlasmicMobilePreletores__VariantsArgs, ReservedPropsType> & // Specify variants directly as props
    /* Specify args directly as props*/ Omit<
      PlasmicMobilePreletores__ArgsType,
      ReservedPropsType
    > &
    /* Specify overrides for each element directly as props*/ Omit<
      NodeOverridesType<T>,
      ReservedPropsType | VariantPropType | ArgPropType
    > &
    /* Specify props for the root element*/ Omit<
      Partial<React.ComponentProps<NodeDefaultElementType[T]>>,
      ReservedPropsType | VariantPropType | ArgPropType | DescendantsType<T>
    >;

function makeNodeComponent<NodeName extends NodeNameType>(nodeName: NodeName) {
  type PropsType = NodeComponentProps<NodeName> & { key?: React.Key };
  const func = function <T extends PropsType>(
    props: T & StrictProps<T, PropsType>
  ) {
    const { variants, args, overrides } = React.useMemo(
      () =>
        deriveRenderOpts(props, {
          name: nodeName,
          descendantNames: PlasmicDescendants[nodeName],
          internalArgPropNames: PlasmicMobilePreletores__ArgProps,
          internalVariantPropNames: PlasmicMobilePreletores__VariantProps
        }),
      [props, nodeName]
    );
    return PlasmicMobilePreletores__RenderFunc({
      variants,
      args,
      overrides,
      forNode: nodeName
    });
  };
  if (nodeName === "root") {
    func.displayName = "PlasmicMobilePreletores";
  } else {
    func.displayName = `PlasmicMobilePreletores.${nodeName}`;
  }
  return func;
}

export const PlasmicMobilePreletores = Object.assign(
  // Top-level PlasmicMobilePreletores renders the root element
  makeNodeComponent("root"),
  {
    // Helper components rendering sub-elements

    // Metadata about props expected for PlasmicMobilePreletores
    internalVariantProps: PlasmicMobilePreletores__VariantProps,
    internalArgProps: PlasmicMobilePreletores__ArgProps
  }
);

export default PlasmicMobilePreletores;
/* prettier-ignore-end */
