// This is a skeleton starter React component generated by Plasmic.
// This file is owned by you, feel free to edit as you see fit.
import * as React from "react";
import {
  PlasmicDesktop4,
  DefaultDesktop4Props
} from "./plasmic/casais/PlasmicDesktop4";
import { HTMLElementRefOf } from "@plasmicapp/react-web";

// Your component props start with props for variants and slots you defined
// in Plasmic, but you can add more here, like event handlers that you can
// attach to named nodes in your component.
//
// If you don't want to expose certain variants or slots as a prop, you can use
// Omit to hide them:
//
// interface Desktop4Props extends Omit<DefaultDesktop4Props, "hideProps1"|"hideProp2"> {
//   // etc.
// }
//
// You can also stop extending from DefaultDesktop4Props altogether and have
// total control over the props for your component.
export interface Desktop4Props extends DefaultDesktop4Props {}

function Desktop4_(props: Desktop4Props, ref: HTMLElementRefOf<"div">) {
  // Use PlasmicDesktop4 to render this component as it was
  // designed in Plasmic, by activating the appropriate variants,
  // attaching the appropriate event handlers, etc.  You
  // can also install whatever React hooks you need here to manage state or
  // fetch data.
  //
  // Props you can pass into PlasmicDesktop4 are:
  // 1. Variants you want to activate,
  // 2. Contents for slots you want to fill,
  // 3. Overrides for any named node in the component to attach behavior and data,
  // 4. Props to set on the root node.
  //
  // By default, we are just piping all Desktop4Props here, but feel free
  // to do whatever works for you.

  return <PlasmicDesktop4 root={{ ref }} {...props} />;
}

const Desktop4 = React.forwardRef(Desktop4_);
export default Desktop4;
